<craft name="button">
    <parameter name="width" type="int" default="6"/>
    <parameter name="height" type="int" default="1"/>
    
    <g layout="centerXYZ()" color="teal">
        <g layout="centerXYZ()" cut=".holes">
            <col spacing="{{width/6}}" class="holes">
                <repeat n="2">
                    <row spacing="{{width/6}}">
                        <repeat n="2">
                            <cylinder radius="{{width / 12}}" height="{{height}}"></cylinder>
                        </repeat>
                    </row>
                </repeat>
            </col>

            <cylinder radius="{{width / 2}}" height="{{height}}"/>
        </g>
        
        <script type="text/openjscad">
            function main() {
                // Border
                return torus({
                    ri: 1,
                    ro: params.width / 2,
                    fni: 6
                }).translate([0, 0, 0.5]).scale([1, 1, params.height]);
            }
        </script>
    </g>

</craft>